#!/usr/bin/env python3
"""Generate high-precision reference vectors for Kairos' fixed-point math.

Values are computed with `decimal` at 60 significant digits and emitted as a Solidity
contract, so `MathLib.lnWad` / `MathLib.sqrtWad` can be differentially tested against a
reference that is far more accurate than the WAD grid itself.

    python3 sim/gen_math_fixtures.py > test/fixtures/MathFixtures.sol
"""

from decimal import Decimal, getcontext
import sys

getcontext().prec = 60

WAD = Decimal(10) ** 18


def to_wad(d: Decimal) -> int:
    """Round-half-even to the WAD grid, matching how the reference is meant to be read."""
    return int((d * WAD).quantize(Decimal(1)))


# Inputs span 24 orders of magnitude either side of 1.0, plus a dense cluster around 1.0
# where swap-induced log returns actually live.
LN_INPUTS = [
    Decimal("0.000000000000000001"),
    Decimal("0.000000001"),
    Decimal("0.0001"),
    Decimal("0.01"),
    Decimal("0.1"),
    Decimal("0.5"),
    Decimal("0.9"),
    Decimal("0.99"),
    Decimal("0.999"),
    Decimal("0.9999"),
    Decimal("0.99999"),
    Decimal("0.999999999"),
    Decimal("1"),
    Decimal("1.000000001"),
    Decimal("1.00001"),
    Decimal("1.0001"),
    Decimal("1.001"),
    Decimal("1.01"),
    Decimal("1.1"),
    Decimal("2"),
    Decimal("2.718281828459045235"),
    Decimal("10"),
    Decimal("100"),
    Decimal("1000"),
    Decimal("1000000"),
    Decimal("1000000000000"),
    Decimal("1000000000000000000"),
    Decimal("1000000000000000000000000"),
]

SQRT_INPUTS = [
    Decimal("0"),
    Decimal("1"),
    Decimal("2"),
    Decimal("4"),
    Decimal("0.25"),
    Decimal("0.0001"),
    Decimal("1.44"),
    Decimal("100"),
    Decimal("12345.6789"),
    Decimal("1000000"),
    Decimal("0.000000000000000001"),
    Decimal("999999999999.999999"),
]


def sol_int(n: int) -> str:
    """Solidity literal with thousands separators, matching `forge fmt`'s house style.

    Emitting one assignment per element keeps every line short enough that the formatter has
    nothing left to do, so CI can diff this file against its generator byte for byte.
    """
    sign, digits = ("-", str(-n)) if n < 0 else ("", str(n))
    groups = []
    while len(digits) > 3:
        groups.insert(0, digits[-3:])
        digits = digits[:-3]
    groups.insert(0, digits)
    return sign + "_".join(groups)


def main() -> None:
    out = sys.stdout
    out.write("// SPDX-License-Identifier: BUSL-1.1\n")
    out.write("pragma solidity ^0.8.28;\n\n")
    out.write("// AUTOGENERATED by sim/gen_math_fixtures.py -- do not edit by hand.\n")
    out.write("// Reference values computed with Python `decimal` at 60 significant digits.\n\n")
    out.write("library MathFixtures {\n")

    out.write("    /// @dev [inputWad, lnWad] pairs.\n")
    out.write("    function ln() internal pure returns (int256[2][%d] memory v) {\n" % len(LN_INPUTS))
    for i, x in enumerate(LN_INPUTS):
        out.write("        v[%d][0] = %s;\n" % (i, sol_int(to_wad(x))))
        out.write("        v[%d][1] = %s;\n" % (i, sol_int(to_wad(x.ln()))))
    out.write("    }\n\n")

    out.write("    /// @dev [inputWad, sqrtWad] pairs.\n")
    out.write("    function sqrt() internal pure returns (uint256[2][%d] memory v) {\n" % len(SQRT_INPUTS))
    for i, x in enumerate(SQRT_INPUTS):
        out.write("        v[%d][0] = %s;\n" % (i, sol_int(to_wad(x))))
        out.write("        v[%d][1] = %s;\n" % (i, sol_int(to_wad(x.sqrt()))))
    out.write("    }\n")
    out.write("}\n")


if __name__ == "__main__":
    main()
